# CQ9: What are the start and end dates of each season?
PREFIX foot: <https://datdinh0923.github.io/SemanticWeb_2025B/ontology/>
PREFIX schema: <https://schema.org/>

SELECT ?season ?label ?startDate ?endDate
WHERE {
    ?season a foot:Season ;
            foot:seasonLabel ?label ;
            schema:startDate ?startDate ;
            schema:endDate ?endDate .
}
ORDER BY ?startDate
