PREFIX foot: <https://datdinh0923.github.io/SemanticWeb_2025B/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <https://schema.org/>

SELECT ?team ?name ?externalDataset ?externalResource
WHERE {
    ?team a foot:FootballTeam ;
          schema:name ?name ;
          owl:sameAs ?externalResource .
    BIND(
        IF(
            CONTAINS(STR(?externalResource), "wikidata.org"),
            "Wikidata",
            "DBpedia"
        ) AS ?externalDataset
    )
}
ORDER BY ?name ?externalDataset
